version: '3.8'

services:
  db:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bajajkart
    ports:
      - "5433:5432"
    volumes:
      - /Users/swapnilsalvi/FSD\ Training/AWS/Docker/container-database-data:/var/lib/postgresql/data
  app:
    build: .
    image: bajajkart-web-app
    container_name: bajajkart-web-app-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bajajkart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db


